name: Update kernel branches

on:
  schedule:
    - cron: "0 0 * * *" # Nightly
  workflow_dispatch: # Allows manual triggering


jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Set week key
        id: week
        run: echo "week=$(date +'%Y-%W')" >> $GITHUB_OUTPUT

      - name: Restore Git bundle cache (weekly)
        uses: actions/cache@v3
        with:
          path: ./bundle-cache
          key: cdn-bundle-${{ steps.week.outputs.week }}

      # https://www.kernel.org/best-way-to-do-linux-clones-for-your-ci.html
      - name: Download Git bundle if not cached
        if: steps.restore-bundle.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./bundle-cache
          CDNBUNDLE="https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/clone.bundle"
          curl -L "${CDNBUNDLE}" -o ./bundle-cache/clone.bundle

      - name: Seed repository from Git bundle
        run: git clone ./bundle-cache/clone.bundle "$GITHUB_WORKSPACE"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Normally pushing to a branch from an Action doesn't trigger push
          # actions.  According to ChatGPT, using a "personal access PAT token"
          # will change that, so these pushes should trigger the test actions.
          # I created the PAT through the UI and then copied it into the
          # "repository secrets" in the UI.
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update branches
        run: .github/scripts/update_branches.sh