name: Update kernel branches

on:
  schedule:
    - cron: "0 0 * * *" # Nightly
  workflow_dispatch: # Allows manual triggering


jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: github/linus/master
          fetch-depth: 0

      - name: Pull from kernel tree
        run: |
          # Using the Github mirror is probably more efficient
          git remote add linus https://github.com/torvalds/linux.git
          git fetch linus

      - name: Merge kernel branch
        run: |
          git merge linus/master --no-edit

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge GitHub Actions config
        run: |
          git merge --no-edit origin/github-base

      - name: Push
        run: |
          git push
